### ISSUE TITLE
Include TeX tool chain for developers who are building vignettes

### ISSUE THREAD

**Issue by seandavi** [rocker-org/rstudio-daily#1]
I'm a little new to rocker.  A Bioconductor user has been using the Bioconductor docker images for doing package development.  Given that the use case for rstudio-daily is to live on the bleeding edge, it seems like a more fully-developed tool chain for development might be useful.  In particular, TeX might be useful.  Any thoughts on the issue?

**Comment by eddelbuettel** [comment]
I think we discussed this in a different ticket for Rocker.  The general view is that the added 1 gb of space is a little heavy for general purpose containers.   You could build on top of ours ...

**Comment by seandavi** [comment]
Just having an answer is all we needed.  Thanks!

**Comment by cboettig** [comment]
Note that a reasonably rich TeX suite is already installed on the
hadleyverse image.

It might be worth putting that same set on the rstudio-daily:verse image,
which is essentially the hadleyverse analog (all packages come from the
github versions)

**Comment by seandavi** [comment]
It would be really nice to have a well-thought-out devel community
container (that could, indeed, be large).  That doesn't need to be your
problem, though.  We'll take a look at the hadleyverse image as a
possibility.

Sean

**Comment by eddelbuettel** [comment]
The problem is that our communities are pretty large, and so is the package universe. "Asymptotically" would we not end up with too large a fraction of all of CRAN?   On the other maybe that large part is still viable...

**Comment by cboettig** [comment]
Right, r-devel and its sanitizer friends are probably your go-to containers
for a well thought-out developer container.  I'm not sure that it's
possible to have a more kitchen-sink version that still appears to be
well-thought-out for everyone.  rstudio-daily:verse fits a particular niche
of development (e.g. cares about compatibility with upstream packages
developed by rstudio, doesn't care so much about things like tex), but
clearly won't be everyone's cup of tea.  Particular communities are welcome
to follow the same model though, building their own Dockerfiles on r-devel
or rstudio-daily in the same way that we do with :verse

I agree that rstudio-daily:verse is not a particularly though-out image
though, represents my own experimentation more than anything.  it might
make sense to have it parallel hadleyverse more closely (e.g. include the
tex installation, since it's not particularly lightweight anyhow).

**Comment by seandavi** [comment]
This is great information--thanks to you both.  The Docker/Rocker universe
is large and diverse, so it is hard to keep up.

Bioc ended up just adding TeX and pandoc to the rstudio/daily for now.  If
we learn anything important that informs the discussion here, I'll try to
remember to come back to update the thread.

**Comment by cboettig** [comment]
Note that pandoc ships with RStudio, and we bind the RStudio version to the
path in rocker/rstudio & rocker/rstudio-daily.  In earlier rocker
iterations, we found that bundling a separate version of pandoc was both
unnecessary and could produce unexpected results, so I don't recommend
adding pandoc separately.
